### ISSUE TITLE
WebStorm 2021.1 render error when terminal is opened with MJML Support 1.8.0

### ISSUE THREAD

**Issue by maxiruani** [timo-reymann/intellij-mjml-support#10]
Hi,

I have installed MJML Support 1.8.0 at WebStorm 2021.1 and MacOS Catalina 10.15.1
Depending on the size of the terminal, the render view blacks out. If the terminal is too big, it breaks the rendering.

Beside this, great plugin! Thank you very much!

Works:
<img width="1500" alt="works" src="https://user-images.githubusercontent.com/1657432/115925939-5a0fe300-a458-11eb-9bb9-37f327805380.png">

Does not works:
<img width="1504" alt="does not works" src="https://user-images.githubusercontent.com/1657432/115925947-5ed49700-a458-11eb-94d1-13746be57d07.png">

**Comment by timo-reymann** [comment]
Hi @maxiruani,
first thank you for using my plugin.
I will take a look at this and come back at you :)

**Comment by timo-reymann** [comment]
I found the problem, the minimal size for the preview was set to the default value with the terminal open, when resizing the terminal over a specific point it simply goes under the minimum size. That leads to an empty panel :) 

Fix will be in marketplace after approval of JetBrains. If you need the fix really urgent, you can also download the zip file from the [release page for 1.8.1](https://github.com/timo-reymann/intellij-mjml-support/releases/tag/1.8.1). 

Would be great if you could give me feedback, it works for you too 👍🏽

**Comment by maxiruani** [comment]
Hi @timo-reymann!
I have installed the 1.8.1 version from the disk and it is working perfectly.
Thanks for the quick reply and fix! 👏
