### ISSUE TITLE
Image path sugestion/autocomplete

### ISSUE THREAD

**Issue by luispaulotoniettefranca** [timo-reymann/intellij-mjml-support#102]
Can we implement an autocomplete or sugestions for local image paths? Would be amazing!

**Comment by timo-reymann** [comment]
Hi @luispaulotoniettefranca,

this would be indeed a nice feature. I will implement it when i have time! ;)

**Comment by timo-reymann** [comment]
Okay that was straightfoward. Will be available with 1.22.0

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2022.01.05-564</a>

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2022.01.05-565</a>
