### ISSUE TITLE
Indent {% %} blocks?

### ISSUE THREAD

**Issue by notflip** [timo-reymann/intellij-mjml-support#103]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using the autoformat function, I notice that {% %} blocks, for example if statements, do not get indented, I'm not sure if this is intentional or not? Is it possible to have the block below indented?
```
{% if type === 'consumer' %}
<mj-section>...</mj-section>
{% endif %}
```

```
{% if shop.isChefpoint() or shop.isLocalDiningShop() %}
{% include "partials/footer.mjml" %}
{% endif %}
```

**Comment by timo-reymann** [comment]
Currently there is no support for template languages, due to the implementation of the plugin. And for now it would be too much effort.

**Comment by timo-reymann** [comment]
also see #11
