### ISSUE TITLE
Cannot associate a Blade PHP file with MJML

### ISSUE THREAD

**Issue by Ririshi** [timo-reymann/intellij-mjml-support#11]
If I write MJML inside a Blade PHP file, to be processed by the [asahasrabuddhe/laravel-mjml](https://github.com/asahasrabuddhe/laravel-mjml) package, PhpStorm will not recognize it as an MJML file. Even when adding my file pattern `*_mjml.blade.php` to the list of MJML-associated file types, my IDE seems to prefer treating the files as Blade files. This isn't the end of the world, but it kind of defeats the purpose of the plugin for me. I'm hoping it would be possible to also add support for this MJML-in-Blade type of workflow.

**Comment by timo-reymann** [comment]
Hello @Ririshi,
do you have some example file for me? THat would make it easier to check :)

**Comment by timo-reymann** [comment]
So i set up a project locally with laravel and the package you linked.

Associating the file type `*_mjml.blade.php` works, but only after restarting IntelliJ. I guess this is because of the duplicate file type association.

The downside of this is you loose the blade autocomplete and highlighting. I will take a look if i can implement this.

**Comment by Ririshi** [comment]
Thanks for the reply. I understand it's too much work for a niche feature like I'm asking for. Restarting the IDE seems to work, but the file icon association does not seem to change. Perhaps this is happening because I am using the Atom Material Icons plugin. It's not a game-breaker.

I would rather have MJML support than blade support in this case, so I suppose this works fine for now.

Thanks for the reply! Perhaps in the future, it becomes interesting enough to implement Blade + MJML support.

**Comment by timo-reymann** [comment]
For now i am going to inplement the basic mjml association for `*_mjml.blade.php` in case php is enabled (or you are using PHPStorm). 
For the long run there might be a proper blade integration :)

**Comment by timo-reymann** [comment]
Basic file association is available with [1.11.0](https://github.com/timo-reymann/intellij-mjml-support/releases/tag/1.11.0).
As mentioned in my previous comment for the long term there might be a blade integration.
