### ISSUE TITLE
Add configuration for .mjmlconfig path

### ISSUE THREAD

**Issue by thekip** [timo-reymann/intellij-mjml-support#112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The mjml-core package supports `.mjmlconfig` in `json` and `js` formats. 

Looks like cli autodetects only json `.mjmlconfig` file. But allow explicitly setting path to js version of config. The same true for desktop mjml app. 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1586852/157197213-8ed933b1-ad62-4332-b9be-e8e86ed60d56.png">

The future request is add option to set path to `.mjmlconfig` in intelij integration plugin.

**Comment by timo-reymann** [comment]
Heya @thekip,

thank you for using the plugin and the feature request.

I see this is a valuable feature, proposal is:
-  Adding a file picker to the settings allowing to select an mjml config file
-  Pass the config file path to the rendering script; custom scripts need to handle this on their own -> docs will be updated accordingly

I will try to implement it till the end of next week :)

Kind regards
Timo

**Comment by timo-reymann** [comment]
New settings screen draft:
![image](https://user-images.githubusercontent.com/21024948/158263527-7a5cc7f9-ecc1-4b7e-92c8-7fad783cce27.png)

**Comment by timo-reymann** [comment]
Current status:
- :heavy_check_mark:  settings dialog is ready
- :heavy_check_mark:  rendering script has been prepared
- :warning: renderer needs to use mjml config path from settings
- :warning: bind settings dialog
- :warning: Extend changelog

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2022.03.14-602</a>

**Comment by timo-reymann** [comment]
Will be included in 2.1.0

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2022.03.16-606</a>

**Comment by thekip** [comment]
BTW, now, when path to `.mjmlconfig` is implemented, you can consider deprecating custom rendering script feature. You can achieve the same functionality in more interoperable way by using `preprocessors`. Benefit from implementing preprocessor vs rendering script is it would work out of the box with native app and other extensions which supports `.mjmlconfg.js` (vscode for example)

Example `.mjmlconfg.js`: 

```js
const {etaPreprocessor} = require('./eta-preprocessor');

module.exports = {
  components: [],
  packages: [],
  preprocessors: [
    (mjml) => {
      const result = etaPreprocessor(mjml);

      if (result.error) {
        return errorToMjml(
          'Error while preprocessing file. ',
          result.error,
        );
      }

      return result.mjml;
    },
  ],
};

/**
 *
 * @param {string} title
 * @param {string} errorMessage
 */
function errorToMjml(title, errorMessage) {
  return `
<mjml>
  <mj-body>
    <mj-section>
        <mj-column>
        <mj-text>
            <h1>${title}</h1>
            <pre>${errorMessage}</pre>
        </mj-text>
        </mj-column>
    </mj-section>
  </mj-body>
</mjml>`;
}

```
