### ISSUE TITLE
Recognize template include files with MJML data language

### ISSUE THREAD

**Issue by sgrimm** [timo-reymann/intellij-mjml-support#120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
IntelliJ can recognize files that have both a template language type (Apache FreeMarker, Velocity) and a data language type (HTML, MJML, etc.)

The MJML plugin handles this combination fine when you open the files in the editor: you get syntax highlighting and inspections for both MJML and the template language.

But it doesn't recognize MJML-plus-template include files as valid in `<mj-include>` directives.

For example, my MJML files have `.ftlh.mjml` file extensions and IntelliJ is configured (in Editor > File Types) to recognize `*.ftlh.mjml` as Apache FreeMarker files with a data language of MJML. If I do `<mj-include path="footer.ftlh.mjml" />`, the path is flagged as not resolving to a valid MJML file.

If I rename the include file to have just a `.mjml` extension, not `.ftlh.mjml`, the plugin stops complaining about the path pointing to an invalid MJML file. But then I don't get IDE support for the FreeMarker expressions in the include file, so that's not ideal.

### References

* [InteliiJ template data languages docs](https://www.jetbrains.com/help/idea/template-data-languages.html) (in particular the "Add an extension pattern" section)

**Comment by timo-reymann** [comment]
Hi @sgrimm,
currently its indexing the files and only including mjml file types for autocomplete and validation.
I will take a look how this can be handled. 

Please keep in mind that this can take a while.

Kind regards
Timo

**Comment by timo-reymann** [comment]
Heya,

i found time earlier than expected to implement this.
Works fine for me, will be publicly available with the next version after JetBrains approval.

Kind regards
Timo
