### ISSUE TITLE
TSX syntax broken after latest update 1.11.0

### ISSUE THREAD

**Issue by chrishawn** [timo-reymann/intellij-mjml-support#13]
opened a react tsx file syntax checking was broken. only thing installed since was the mjml update. disabled mjml plugin... syntax checking works again.

**Comment by timo-reymann** [comment]
I can not reproduce this. Can you please create a empty project with tsx files and verify its the same there?

**Comment by chrishawn** [comment]
<img width="600" alt="Screen Shot 2021-05-10 at 10 23 07 AM" src="https://user-images.githubusercontent.com/309639/117683568-cfc6bf00-b179-11eb-9ea6-08acbe263ae3.png">

**Comment by chrishawn** [comment]
if i disable mjml plugin no more red squiggles
