### ISSUE TITLE
Mjml plugin doesn't work

### ISSUE THREAD

**Issue by PttRulez** [timo-reymann/intellij-mjml-support#148]
### What happened?

No highlighting, no hints, nothing. Just installed it and for some reason nothing has chaged

### OS

Linux

### What IDE are you facing the problem in?

PhpStorm

### Problem description

No highlighting, no hints, nothing. Just installed it and for some reason nothing has chaged

### Expected behaviour

Highlighting syntax and hints

### Actual  behaviour

Nothing changed

### Steps to Reproduce

don't know :)

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Have you already tried restarting the IDE?

Do you see file iconsf or the MJML files?
