### ISSUE TITLE
File resolution problem

### ISSUE THREAD

**Issue by ClassTerr** [timo-reymann/intellij-mjml-support#159]
### What happened?

IDE keeps warning me that a file could not be resolved despite the fact everything works.
![image](https://github.com/timo-reymann/intellij-mjml-support/assets/30635839/6095f097-9921-42ed-a5fa-cab442fd3a3c)
Even more, IDE suggests this exact path to me while autocomplete is triggered.
![image](https://github.com/timo-reymann/intellij-mjml-support/assets/30635839/385c739d-270a-4dc5-9aa8-7f8d7cf1bf44)
I am not quite sure if this is related to this plugin but it seems a bit strange to me.

### OS

Windows

### What IDE are you facing the problem in?

Rider

### Problem description

The file is not recognized, so I can't Ctrl+Click on it to navigate.

### Expected behaviour

The file should be resolved by IDE

### Actual  behaviour

The file is not resolved.

### Steps to Reproduce

Open empty folder with Rider.

Create 2 files:

`Test.mjml`
```
<mjml>
    <mj-head>
        <mj-preview>
            <!-- TODO Add mail preview -->
        </mj-preview>
    </mj-head>
    <mj-body>
        <mj-include path="Partials\Header.mjml"></mj-include>
    </mj-body>
</mjml>
```

`Partials/Header.mjml`
```
<mjml>
    <mj-head>
        <mj-preview>
            <!-- TODO Add mail preview -->
            Hello from header
        </mj-preview>
    </mj-head>
    <mj-body>
        <mj-section>
            <mj-column>
                <mj-image width="100px" src="https://mjml.io/assets/img/logo-small.png"></mj-image>
                <mj-text>Hello from header</mj-text>
                <mj-divider></mj-divider>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

The error will be displayed at `Test.mjml:8` - 

> Cannot resolve file 'Partials\Header.mjml'

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Heya,

yes, that is definitely related to the plugin.
Will check for a fix in the coming days and will keep you up to date when the fix is available.

Cheers,
Timo

**Comment by timo-reymann** [comment]
Heya,

so the feature itself seems to work fine. Can you verify this actually renders with MJML? I am not entirely sure if that works with the windows paths (basically the weird Microsoft slash)

**Comment by ClassTerr** [comment]
Yep, it renders mjml correctly, just a warning related to path.
![image](https://github.com/timo-reymann/intellij-mjml-support/assets/30635839/2875cf47-fe42-4feb-b7dc-1f7619f07595)

**Comment by ClassTerr** [comment]
I just realized that this slash / works just fine, but it's not windows style and works not so good with default Rider file autocomplete behavior.

**Comment by timo-reymann** [comment]
So the problem is: I use `VfsUtilCore#findRelativeFile` which internally does the following:

```java
uri = uri.replace('\\', '/');
```

So, basically “fixing” the path. As far as I know, this is the recommended API to use. 

As this is just a cosmetic thing imho and windows is not a first-class-citizen I dont want to invest time into building a workaround for it.

So sorry, but I will keep it as it is.
