### ISSUE TITLE
MJML components are allowed in <mj-attributes>

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#16]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Tool: MJML version 4.9.0
* Host OS: Current Win10

## Problem description

I'm setting personal defaults in MJML. In this case, I'm setting `<mj-body>` > `background-color`.

```xml
<mj-head>
   <mj-attributes>
      <mj-body background-color="white" />
   </mj-attributes>
</mj-head>
```

### Expected Behavior

No warning.

### Actual Behavior

The editor warned, "mj-body cannot be used inside mj-attributes, only inside mjml".

### Steps to Reproduce

```xml
<mjml>
   <mj-head>
      <mj-attributes>
         <mj-body background-color="smokewhite" />
      </mj-attributes>
   </mj-head>
   <mj-body>
      <mj-section><mj-column><mj-text>
         Hello!
      </mj-text></mj-column></mj-section>
   </mj-body>
</mjml>
```

### Important Factoids

Nothing atypical known in my environment.

The MJML Desktop App does not report this error. (But maybe both should! That isn't my preference.)

### References

* https://documentation.mjml.io/#tooling
* Perhaps MJML source code does not support the wording of this warning. In the distribution package, file node_modules/mjml/dependencies.js includes the line,

```xml
'mj-attributes': [/^.*^/],
```

Perhaps that line means "all MJML components". (My interpretation of MJML source code is imperfect. That's my best guess.)

**Comment by timo-reymann** [comment]
First analysis:

https://github.com/timo-reymann/intellij-mjml-support/blob/main/src/main/kotlin/de/timo_reymann/mjml_support/tagprovider/BuiltInMjmlTagInformationProvider.kt#L54

Should be set to toplevel and mj-attributes.
