### ISSUE TITLE
Dark and Light theme preview

### ISSUE THREAD

**Issue by ClassTerr** [timo-reymann/intellij-mjml-support#169]
### Description

I use this plugin to develop my mjml templates right inside of Rider. It allows me to render my template using my rendering API right inside my IDE, so it is very simple and useful for me. Thanks for this plugin.

But there is a thing that I am missing - changing a background color for the email. Right now it looks like this:
![image](https://github.com/timo-reymann/intellij-mjml-support/assets/30635839/c9a93ea6-b51f-44be-b378-123c54c0674c)

I want to see how my email will look like in both light and dark mode without changing a theme of my IDE. It will be great if there will be some switch between them in this panel
![image](https://github.com/timo-reymann/intellij-mjml-support/assets/30635839/3bc8576c-9a97-4772-8302-5cec550e78d0)

**Comment by timo-reymann** [comment]
Heya @ClassTerr, 

thanks for bringing this one up and using my plugin! :) 

Sounds like a good feature request, will take a look and report back to you once its generally available.

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2023.10.10-868</a>

**Comment by ClassTerr** [comment]
Looks perfect! Thank you for a quick response and implementation!

I just wondering if it's working with
```
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
```
and `@media (prefers-color-scheme: dark) {}` media selector?

**Comment by timo-reymann** [comment]
Released with 3.1.0 to marketplace :)

**Comment by timo-reymann** [comment]
> Looks perfect! Thank you for a quick response and implementation!
> 
> I just wondering if it's working with
> 
> ```
> <meta name="color-scheme" content="light dark">
> <meta name="supported-color-schemes" content="light dark">
> ```
> 
> and `@media (prefers-color-scheme: dark) {}` media selector?

Nope, currently it only sets the background color of the browser panel. Will check if is possible with the JCEF implementation by JetBrains to emulate dark/light color scheme using the dev tools

**Comment by timo-reymann** [comment]
Didnt find a way to emulate it. Closing for now.
