### ISSUE TITLE
MJ-RAW is encoding HTML tags (<>) when generating HTML from within IntelliJ plug-in (PHPStorm)

### ISSUE THREAD

**Issue by chrisconverse** [timo-reymann/intellij-mjml-support#196]
### What happened?

The greater than and less than characters are being encoded when wrapped in the mj-raw tags.

### OS

Darwin

### What IDE are you facing the problem in?

PhpStorm

### Problem description

I am trying to pass pass in a variable set by my organization to handle unsubscribe links
`<mj-raw><%@ include view=‘ORGUnsubscribeLink’ %></mj-raw>`

### Expected behaviour

I expect the <mj-raw></mj-raw> tag to be replaced with the HTML code inside:
`<%@ include view=‘ORGUnsubscribeLink’ %>`

### Actual  behaviour

The <mj-raw> tags appear in the final HTML, and the HTML code inside the mj-raw is encoded, Below is what appears in the HTML:
`<mj-raw>&lt;%@ include view=&#x2018;ORGUnsubscriptionLink&#x2019; %&gt;</mj-raw>`

### Steps to Reproduce

Add the following code to an MJML document, then check the HTML preview:
`<mj-raw><%@ include view=‘ORGUnsubscribeLink’ %></mj-raw>`

Turns into the following:
`<mj-raw>&lt;%@ include view=&#x2018;ORGUnsubscriptionLink&#x2019; %&gt;</mj-raw>`

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
The plugin and the built-in renderer does not support template languages.

There is only user contributed detection of MJML files when they match `*_mjml.blade.php` and I do not plan to support it.

What you can do is creating a custom renderer script that suits your needs - in this case adds the template include to the HTML before rendering with MJML.

For more information check the tutorial on the plugin page: https://plugins.jetbrains.com/plugin/16418-mjml-support/tutorials/custom-rendering-script
