### ISSUE TITLE
Possible Errors or Warnings for Some Uses of <mj-include>

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#20]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Perhaps the current data structures don't support detecting useful Warnings or Errors, in at least one case.

Perhaps BuitlInMjmlTagInformationProvider.kt line 69 (about mj-include), `allowedParentTags = PARENT_ANY` means, loosely, "any MJML component may be a parent to `<mj-include>`."

As I understand it, MJML design calls for prohibiting `<mj-include>` in at least these components.

tag                         | tag                           | tag
---------------------|-----------------------|--------------------
mj-accordion-text  | mj-preview              | mj-text
mj-accordion-title  | mj-raw                    | mj-divider
mj-button               | mj-social-element  | mj-font
mj-carousel-image | mj-style                  | mj-image
mj-breakpoint        | mj-table                 |
mj-navbar-link       | mj-title                   |

IMHO, it would be a valuable feature of this code to issue Warnings or Errors when the code detects any of these attempts.

Further, perhaps it would be best to issue Errors for some components and Warnings for others. Perhaps `<mj-text>` (for which using `<mj-include>` might be tempting and would fail) deserves an `Error` to give authors early warning of problems. Perhaps that logic holds for all components.

On the other hand, perhaps `<mj-breakpoint>` deserves only a `Warning` because there's a small chance of problems for authors. I tried an example of `<mj-include>` with `<mj-breakpoint>`. (It made no real-world sense!) Judging by code in the HTML, MJML reacted to the "business part" of `<mj-breakpoint>`. Judging by the rendering, MJML may have fully ignored the content between the tags. If it's consistent that way, perhaps we'd better serve the authors to not use an Error.

Thanks for this great code! It's valuable to the MJML/JetBrains community.

### References

In Slack conversations, the MJML team has indicated `<mj-include>` is not usable in components with `static endingTag = true` in their class declaration, and otherwise usable. All components in the above list except the last three include that syntax. IMHO, the last three belong on the list. Perhaps others belong there, too; I haven't done a rigorous check.

**Comment by LucPestille** [comment]
Also maybe related, I've found that using an mj-include for css files provokes a warning, when it's suggested by the docs themselves; https://documentation.mjml.io/#mj-include

**Comment by timo-reymann** [comment]
> Also maybe related, I've found that using an mj-include for css files provokes a warning, when it's suggested by the docs themselves; https://documentation.mjml.io/#mj-include

Thank you for the report @LucPestille, thats not directly related to this, but it should be indeed supported. I will create a separate ticket for this :)

**Comment by timo-reymann** [comment]
Proposed solution is to add support for endingTag, that automatically fixes the problem with the mj-include any other elements that are going to be included.

When a element can not contain any children, it should be an error rather than a warning imho.

**Comment by timo-reymann** [comment]
I currently plan to have a "beta/nightly-channel" for testing changes like this before releasing them. 

So the implementation is ready, but not downloadable via marketplace. Once the new release channel is setup i will add a comment/link with more instructions :)

**Comment by timo-reymann** [comment]
Unstable channel is here, for more info take a look at the README: https://github.com/timo-reymann/intellij-mjml-support#you-live-on-the-edge

First snapshot version has new changes and is pending approval:
![image](https://user-images.githubusercontent.com/21024948/122815487-ce8ac500-d2d5-11eb-94c3-98e4077c386c.png)

@GarryFlemings would be nice if you could test it and give some feedback here! :)

**Comment by timo-reymann** [comment]
Released with 1.15.0

**Comment by GarryFlemings** [comment]
### Subject code

[mj-include_allowed.txt](https://github.com/timo-reymann/intellij-mjml-support/files/6744257/mj-include_allowed.txt)

### Comments

Preferred:
* Each usage of any of the twelve MJML elements containing ` static endingTag = true` plus "&lt;mj-text>" causes an error report, "Tag [MJML element] can not have child elements".
* No other statement of the template cases any report.
* All resulting rendering is expectable.

Actual:
* MJML Support 2021.06.29-307 works with MJML 4.10.1 and the subject code as preferred.
