### ISSUE TITLE
How to enable live preview of MJML?

### ISSUE THREAD

**Issue by satvug** [timo-reymann/intellij-mjml-support#204]
### What happened?

Hi, how do I enable live preview of MJML? It says something about having to have JS / Node modules enabled? How do I enable that in Rider? Thanks a lot!

### OS

macOS 14.6.1

### What IDE are you facing the problem in?

JetBrains Rider 2024.1.2

### Problem description

Hi, how do I enable live preview of MJML? It says something about having to have JS / Node modules enabled? How do I enable that? Thanks a lot!

### Expected behaviour

I can see the live preview of MJML

### Actual  behaviour

I don't see any live preview

### Steps to Reproduce

n/a

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
In Rider Node.js should be enabled by default, unless you disabled it.

Also see Jetbrains Docs: https://www.jetbrains.com/help/rider/Developing_Node_JS_Applications.html

**Comment by satvug** [comment]
There's still zero information about how to make this plugin work. How do I make the mjml preview window open?
Node.js and js/ts is enabled in plugins.

<img width="982" alt="image" src="https://github.com/user-attachments/assets/c727db90-2e46-4e31-b0a2-805987165672">

**Comment by timo-reymann** [comment]
Have you followed the steps mentioned in the docs? Especially configuring a Node.js interpreter?

If Node is enabled the Preview panel will be visible. If it is not configured correctly it will show up in the Preview.

Can you share your Node settings and maybe a open mjml file (with project explorer & editor visible)?

**Comment by satvug** [comment]
I am so sorry, it seems like the preview might always have been there, I just did not find the "preview" buttons toolbar, here visible in the upper right corner, besides my file tabs. Easy to miss for me apparently.

![image](https://github.com/user-attachments/assets/07305ddb-01d9-4982-9fae-4f077f45df90)

Sorry for the bad bug report, it's working just fine. Thanks for your work!
