### ISSUE TITLE
Support `filename.mjml.twig`

### ISSUE THREAD

**Issue by simoheinonen** [timo-reymann/intellij-mjml-support#208]
### Description

Would be nice if file names like `filename.mjml.twig` would be supported out of the box!

**Comment by timo-reymann** [comment]
One can liberally change this in IDE settings. I wont force it tho, as the plugin does not support template languages.

So one has to decide either to have mjml or template language highlighting.

See https://www.jetbrains.com/help/idea/creating-and-registering-file-types.html#configure-associations-between-filename-patterns-and-file-types on how to configure this.
