### ISSUE TITLE
Show HTML is not working

### ISSUE THREAD

**Issue by Shehab-Muhammad** [timo-reymann/intellij-mjml-support#226]
### What happened?

when attempt to show html nothing happen
still showing the UI components
![image](https://github.com/user-attachments/assets/2f33ea37-41a9-46d2-995b-bef593a8a94c)
I'm using GoLand 2024.3

### OS

Linux

### What IDE are you facing the problem in?

GoLand

### Problem description

click on "show html" has no effect

### Expected behaviour

expected to show html instead of UI

### Actual  behaviour

still showing the UI

### Steps to Reproduce

create mjml template and click on show html

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Which plugin version are you using?

**Comment by timo-reymann** [comment]
I can't reproduce this with GoLand 2024.3 and the plugin in version 3.6.0 unfortunately :/

**Comment by Shehab-Muhammad** [comment]
@timo-reymann using version 3.6.0 of the plugin
now it's working looks like inconsistent issue
