### ISSUE TITLE
code review inside Markdown file?

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#23]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### First of two sets of lines from MJML's doc\components_2.md:

> ```xml
> 
> <mjml>
>   <mj-body>
>     <mj-include path="./header.mjml" />
>   </mj-body>
> </mjml>
> ```

In my WebStorm, I get a Warning on the include file title, `./header.mjml is not resolving to a valid mjml file`.

There's basis for the warning.

At the same time, this code is in a Markdown file. Perhaps detection of this condition in a Markdown file is not necessary?

#### Second of two sets of lines from MJML's doc\components_2.md:

```xml
<!-- main.mjml -->
  <mj-include path="./styles.css" type="css" />
  <mj-include path="./inline-styles.css" type="css" css-inline="inline" />
```

In my WebStorm, I get a "red squiggle" under the start of the second `mj-include`. Flying the cursor over the area gives me a message, "Multiple root tags".

(Blush.) Presuming this message is valid somewhere, I might not know what caused it to display and
I might not know how to fix it.

As above, this code is in a Markdown file. Perhaps detection of this condition in a Markdown file is not necessary?

### Priority

Both are nice-ish to change. Neither is either essential or urgent. :)

**Comment by timo-reymann** [comment]
Okay so from the first analysis, i see two things:

**xml leads to the duplicate root tag inspection**
There is nothing i can do about it, thats coming from the builtin xml plugin

**the inspection with the include shows up in xml context -> that should not be the case in the first place**
mj-include should not be validated inside xml blocks

**Comment by timo-reymann** [comment]
Fixed inspection in xml:
https://github.com/timo-reymann/intellij-mjml-support/commit/443fd481f9b09f71a08d4d8d01e4fe93f879c4d9
