### ISSUE TITLE
don't close open editor windows when MJML Support gets disabled

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#35]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Scenario: I experienced a WebStorm action with MJML Support active. I hoped to learn whether that action is in MJML Support code. I temporarily disabled MJML Support. All my open MJML editor windows closed.

### Potential Feature

MJML Support could leave the MJML editor windows open.

### Considerations

I might still want to work on them.

They might not be saved. I might not want to save them yet and at the same time not want to lose their changes.

Before I found MJML Support, it was a normal condition to work on MJML files without MJML Support.

Neither critical nor urgent.

**Comment by timo-reymann** [comment]
The problem here is that a custom FileEditorProvider is used, when the plugin gets disabled it simply closes all tabs using that provider. Unfortunately thats outside the scope of this plugin.

There is a way to react on the uninstall event, but it would be not very stable/reliable.
