### ISSUE TITLE
don't provide feedback for Markdown files

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Background

I'm editing a Markdown file. I see an Error, "Multiple root tags." And many instances of a Warning, "Warning:(29, 81) Line is longer than allowed by code style (> 80 columns)".

### Possible new feature

If feedback on Markdown is out-of-scope to MJML Support, suppress Errors and Warnings on this file type.

Similar for other file types?

**Comment by timo-reymann** [comment]
This issue is related to #23, as mentioned here it is currently not intended to make markdown files behave differently.

Nevertheless i think you are talking about the xml-Snippets in the MJML docs? - There are a different language and therefore not processed by the plugin :)
