### ISSUE TITLE
2021.07.05-316: Failed to render mjml using helper script

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#41]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* Windows 10 Home 20H2 19042.1052
* WebStorm 2021.1.3 #WS-211.7628.25
* MJML Support 2021.07.05-316

## Problem description

For every MJML file, this appears in the preview pane:
![Screenshot 2021-07-07 105139](https://user-images.githubusercontent.com/14095071/124791898-1cc4d880-df12-11eb-89c1-bf03d632a5db.png)

Also, no MJML file has any Errors or Warnings. Nothing noted in Event Log.

This feedback comes after loading the new MJML Support and after restarting WebStorm.

**Comment by timo-reymann** [comment]
May be releated to the new exception in #34.

But the ceck if the builtin render should be used currently doesnt care about the default. Fix will be available with the new snapshot.

**Comment by GarryFlemings** [comment]
2021.07.07-320: The graphic above no longer appears. Rendering shows instead.

Maybe Errors and Warnings are still off? The only such messages I notice are like "XML tag has empty body", responding to "<td></td>". Maybe that's from the XML interpreter, not from MJML Support?

**Comment by timo-reymann** [comment]
Can you check if there is an exception and the file icons have been loaded?

**Comment by GarryFlemings** [comment]
I'm working on a long-ish email with some include files. For each include file (but not for the root file), I got
![Screenshot 2021-07-09 113720](https://user-images.githubusercontent.com/14095071/125110593-634d3b00-e0aa-11eb-87e6-a21847e1e80c.png)

In blue is one of my file titles. All messages are the same, except for that.

The blue "show balloon" repeats the message in full in a pop-up box, except for leaving out the "show balloon" part.

All messages repeat for each rendering. I haven't detected whether that they affect rendering.

I've noticed these for a while. I haven't mentioned them because they haven't particularly annoyed me and I had so little to report about them. This report doesn't represent all I've seen.

Sometimes the fields filled here with "replace" and "undefined" are different. I'll report on some of those next time I see them, if you wish.

**Comment by timo-reymann** [comment]
File icon loading simply means the mjml icon is used for the files, when this is the case the language support is working properly. But as the preview is working that seems to be the case.

That output is coming directly from mjml rendering and unfortunately outside of the scope of the plugin.

Errors and warnings are working for me, you are using the latest version right?

**Comment by GarryFlemings** [comment]
In the Project View (listing files in the project directory), each MJML file has the MJML icon.

Out of scope? I'll try to report only those the desktop app doesn't report. And I'll mention that in my reports. If I don't mention it, I may have forgotten to check it.

Report of Errors and Warnings not working: I take it back--my code is better than I remembered. When I introduce new problems, they get a report right away.

Version: still 2021.07.07-320 (one upgrade since filing this ticket). WebStorm seems to think that remains current.

Nice work. That big graphic is gone. It looks like everything else I reported is out of scope. Solid! 🏆 

I'll close this. Please reopen if I've missed something you want to keep thinking about.
