### ISSUE TITLE
Warning: "Unknown attribute line-height for mjml tag mj-accordion-text"

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#44]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

- Windows 10 Home 20H2 19042.1083
- WebStorm 2021.1.3 #WS-211.7628.25 built on June 30, 2021
- MJML Support 2021.07.09-322

## Condition
I'm working on an email (the same email described in #43). It has several include files, one of them an external CSS file containing this line inside an `mj-attributes` element:

```
<mj-accordion-text line-height="1.6" />
```

### Actual Behavior

With small horizontal lines in the editor and on the "Problems" tab (not in the "Event Log"), I see this report (not preferred).

```
Unknown attribute line-height for mjml tag mj-accordion-text
```

[Image in #43.]

### Steps to Reproduce

Working on my email.

### References

`line-height` is present for `mj-accordion-text` in [MJML documentation for `mj-accordion`](https://documentation.mjml.io/#mj-accordion).

**Comment by timo-reymann** [comment]
fixed in https://github.com/timo-reymann/intellij-mjml-support/commit/c1cea5856ffc9893f0e5de834bf33d10d6a45630, accidentally referenced the wrong ticket 🤦

**Comment by GarryFlemings** [comment]
Checked under the same conditions in MJML Support 2021.07.12-332. The report is absent. Yay!

Thanks for the quick response.
