### ISSUE TITLE
"TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#50]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

- Windows 10 Home 20H2 19042.1151
- WebStorm 2021.1.3 #WS-212.4746.80 built on July 23, 2021
- MJML Support 2021.08.03-356

## Expected Behavior

No reporting.

### Actual Behavior

I continue to work on the email template I mentioned in #43. (It's a good thing it isn't for a client!)

In the WebStorm Event Log (perhaps it has another name in another JetBrains product), I see six reports similar to:

![image](https://user-images.githubusercontent.com/14095071/128274470-29559d05-da52-4300-901c-0c2f098ff65d.png)

In case any of this is important. (This may be both too much and too little info! 😁😌)

- The six reports have identical wording except for file titles.
- Three file titles are in the six reports; the second group of three repeats the first.
- This template has include files.
- All three reported files are include files; none is the base file.
  - Two of the files are also CSS files. They're the only CSS files for the template.
  - The third file is a plain-MJML file.
- All three reported files have tabs in WebStorm editor windows.
- WebStorm editor windows
  - WebStorm has two editor windows open: left and right.
  - The left editor window has three tabs: the root MJML file, the plain-MJML reported file, and a TXT file.
  - The right window has four tabs: the two reported CSS files, the root MJML file, and an HTML file.
  - Among the seven tabs, all five MJML files, including the CSS files, are in "Editor only" mode for MJML Support.
  - If I change the right window tab for the base MJML file to "Preview only", the template renders without missing any files. Indeed, there are clear indications for each of the three reported files that they are influencing the rendering. A one-character change to the plain-MJML reported file renders appropriately. The rendering process does not cause the reports above.
- This point establishes that all executables and data were very fresh when WebStorm generated the reports. If that's not relevant, ignore this point.
  - I installed some Windows Updates, thus needing to restart the computer. Very soon after the operating was ready, I started WebStorm, opened my project, and noted some errors. Because I suspected those errors were from another plug-in, I disabled that plug-in and thus needed to restart WebStorm. Very soon after WebStorm was ready again, I noted the errors were absent. I enabled that plug-in; those errors returned. They're not yours.
  - With both those WebStorm starts, the reports above were present in the Event Log.
- The only time WebStorm has generated these errors were on those two WebStorm starts.
- I'm not sure either that these reports were in 2021.07.09-322 or were not in. I don't remember seeing them.

**Comment by timo-reymann** [comment]
I have seen this several times with a specifc mjml constellation and think this is a bug directly in mjml. I will try to reproduce it, do you have a code sample where this occurs? Or is the mentioned file to big to find out where this happens?

**Comment by timo-reymann** [comment]
Alright, so it seems this is the exact same problem described in https://github.com/mjmlio/mjml/issues/2200.

So when you create a new mail from scratch and there is no mjml or mj-body tag it will fail with this "error message".

Checking if both tags are present and valid before each rendering might be to time consuming and cripling performance. I will try to find a performant way or maybe even better create an change in the mjml project to provide a better error message for such cases?

**Comment by GarryFlemings** [comment]
> Alright, so it seems this is the exact same problem described in ...

Well ... maybe not. And maybe yes.

As to "maybe not": My template has include files; the template discussed there did not. The template discussed there is equivalent to my root template (the one calling the include files; in my case no include file calls another). That template had no `<mjml><mj-head></mj-head><mj-body></mj-body></mjml>`; mine root template has all of those. My root template isn't getting the report.

As to "maybe yes": All three files getting reports are include files.

"You can wrap your external mjml files [include files, above] inside the default mjml > mj-body tags to make it easier to preview outside the main template." https://documentation.mjml.io/#mj-include

Said from the other perspective, the default mjml > mj-body tags are optional in include files.

My template has nine include files, including the two CSS files. None of the nine include files has the default mjml > mj-body tags.

All the include files assigned tabs in WebStorm editor windows received reports. No other include files received reports.

As I mentioned in the original post, the rendering properly reflected the use of all include files.

Conjectures:
1) The inspection causing the reports is associated with editor windows.
2) Using files for rendering, if they're not in an editor window, does not trigger this inspection.
3) The inspection causing the reports could performantly check whether the file it's about to check is an include file. If it is, it could not run the inspection.

But then again, there are lots of moving parts in these pieces of code. Factors I don't know about could easily prove my conjectures wrong.

**Comment by timo-reymann** [comment]
Yes you are right the inspection (a rendering error directly from mjml) occurs only for imports (where there is no mjml > mj-body). This could be a performant solution to "disable rendering" for files that are included and are not valid mjml standalone files, thats a nice idea.

**Comment by timo-reymann** [comment]
UPDATE:
Parsing xml with the jdom is actually pretty fast and has only very small affect on rendering time, so this is a smooth way to check this for includes as well for "wip files" to prevent the indexOf error

**Comment by GarryFlemings** [comment]
### Used versions (where different)
- MJML Support 2021.08.05-361

### More info:
I tested the above again. Slightly different conditions:
- Not so recent a start of the operating system.
- On the other hand, maybe the same results come from a start of WebStorm.
- Further, maybe the same results come from a new start of the project in WebStorm.
- Three conditions
  - Setting files into editor tabs, then closing and restarting WebStorm.
  - Same files into editor tabs, closing the project, and restarting the project within the same WebStorm session.
  - Other actions in editor tabs.

For these tests, the editor windows were:
- Left window: five files
  - The MJML root file
  - Three MJML include files, one also appearing in a right window editor tab
  - One TXT file
  - All four MJML files were in "Editor only" mode in MJML Support.
- Right window: Five files
  - The MJML root file; "Preview only" mode in MJML Support
  - Two MJML CSS include files 
  - One other MJML include file, also appearing in a left window editor tab
  - One HTML file
  - Excepting for the root file (in "Preview only" mode), remaining MJML files are in "Editor only" mode
 
#### Setting files into editor tabs, then closing and restarting WebStorm.

Observed:

First test run
- Eight reports (non-preferred)
  - First three: Consistent with being the three MJML include files in the left window
  - Next three: Consistent with being the three MJML include files in the right window
  - Next one: Consistent with one of the include files in the left window not also appearing in a right window editor tab
  - Last one: Consistent with the include file appearing in both a left and right window editor tab 
  - No reports for: The base file (eight MJML Support mode tested), the TXT file, or the HTML file (as preferred)

Second test run
- Eleven reports (non-preferred)
  - First six: Identical to the first six above.
  - Next two: Consistent with being files from the left window, one not also appearing in the right window and the duplicate file
  - Last three: Identical to reports 4, 5, and 6 here (the three MJML include files in the right window)
  - No reports for: The base file (eight MJML Support mode tested), the TXT file, or the HTML file (as preferred)

Interpretation
- There's some ambiguity in the above because of test design. Perhaps some cases of attributed to the file represented on both the left and right screens are not attributed to the proper instance. I was interested in seeing whether only one instance would earn a report; that didn't happen.
- No explanation for differing results in the two runs. Perhaps there's a relevant factor I didn't control for.

#### Setting files into editor tabs, closing the project, and restarting the project within the same WebStorm session.

Observed:

First test run
- Six reports (non-preferred)
  - Identical to the first six reports above.
  - No reports for: The base file (eight MJML Support mode tested), the TXT file, or the HTML file (as preferred)

Second test run
- Six reports (non-preferred)
  - Identical to the first six reports above, but in a different order. The first two reports were from the left window, then one from the right, two for the duplicate file (presumably one for each window), and the last from the right window.
  - No reports for: The base file (eight MJML Support mode tested), the TXT file, or the HTML file (as preferred)

Interpretation:
- Ditto above about ambiguity and test design. Also ditto above about differing results.
- I kinda hoped we'd see the same reports in all four of these runs. Maybe it's more complicated that anticipated.

#### Other actions in editor tabs

Observed: Each time I put a project include file in the editing window intending to open it in a new tab, it opens and generates a new report.

Observed: Each time I move a file tab to a different position among the tabs shown, it generates a new report.

I hope this helps!

**Comment by timo-reymann** [comment]
You were a bit to fast, latest snapshot including the changes is [2021.08.06-367](https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot/131427)

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.06-367

Repeated the test (only one test run). No reports in the Event Log (as preferred).

Good news!

**Comment by timo-reymann** [comment]
Thank you for testing, i am closing this ticket and it will be included in the next release! 🥳
