### ISSUE TITLE
WebStorm restart inconsistent in setting MJML Support "Editor/Preview/Both" mode

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#53]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

- Windows 10 Home 20H2 19042.1151
- WebStorm 2021.1.3 #WS-212.4746.80 built on July 23, 2021
- MJML Support 2021.08.05-361

## Expected Behavior

After WebStorm restart, editor tabs always restore to the previous editor windows (left or right or top or ...) in the previous order and MJML files restore to the previous MJML Support "Editor/Preview/Both" mode.

Ideally, if the user closes WebStorm without closing the project, WebStorm would close the project before continuing the shutdown so this case would be covered.

In all the above cases, MJML Support might be able to contribute here only if MJML Support gets a "close" signal from WebStorm. I'm hoping.

### Actual Behavior

Either of

- Editor tabs don't always get the previous version of the MJML Support "Editor/Preview/Both" mode on WebStorm restart.
- WebStorm restores with the same editor windows (always left and right in my usage), but only one tab each, always different files and from the project, presumably each of them one of the files from the respective window.

### Test Condition

For these tests, the editor windows were:
- Left window: five files
  - The MJML root file
  - Three MJML include files, one of those also present in a right window editor tab
  - All four MJML files were in MJML Support "Editor only" mode.
  - One TXT file
- Right window: Five files
  - The MJML root file; MJML Support "Editor/Preview/Both" mode defined later
  - Three MJML CSS include files; "Editor only" mode
  - One other MJML include file, also present in a left window editor tab
  - One HTML file

### Steps to Reproduce, "Editor tabs don't always get ..."

Baseline test condition: Right window MJML root file in MJML Support "Editor only" mode

Action: Close WebStorm. Give it several seconds to be sure it has time to finish closing. Start WebStorm.

Observed: All ten files reappear in the previous tabs and order. All MJML files are (as previously) in MJML Support "Editor only" mode.

Interpretation: As preferred.

Second test condition: The same as the baseline, but with the right window MJML root file in MJML Support "Preview only" mode.

Same action.

Observed:

- All ten files reappear in the previous tabs and order. The MJML file previously in "Preview only" mode is in "Preview only" mode (as preferred).
- All other MJML files are (distinct from previously) in MJML Support "Preview only" mode (non-preferred). 
 
Interpretation: "Editor only" mode would be better for the latter files.

### Steps to Reproduce, "WebStorm restores with the same editor"

Tough one. I've seen this one several times over some weeks, but I have no "Steps to Reproduce". I _think_ this has always happened on WebStorm restart when I had closed WebStorm without previously closing the project; I cannot be sure.

This condition did not occur in my testing for "Editor tabs don't always get ..."

### Important Factoids

~~I'll soon enter a bug report that may be related to the portion, "Editor tabs don't always get ..." It's about opening new editor windows. I'll reference this one there.~~

This may be related to #54 "inconsistent file opening".

**Comment by timo-reymann** [comment]
Currently the editor uses the "editor only" mode per default for every new instance and it is not persisted across restarts.

This might be a feature that impacts startup performance with a lot of mjml files open, might be worth to add a setting to toggle the behaviour :) 

Nice idea though!

**Comment by timo-reymann** [comment]
Will be available  with the next snapshot. Works fine so far with all 3 preview modes for me.

In case there are problems feel free to reopen the ticket.

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.06-367

### About: "Editor tabs don't always get ..."

Baseline test condition: Repeated. Same observations (as preferred).

Second test condition: Repeated.

Observed:

In the right editor window and the tab for the root MJML file (in "Preview mode", per test), the following appears (non-preferred):

![image](https://user-images.githubusercontent.com/14095071/128639031-34f92753-19fe-4f1c-a52d-2b792bef44fd.png)

The root MJML file contains appropriate `<mjml><mj-head></mj-head><mj-body></mj-body></mjml>` tags.

### About: "WebStorm restores with the same editor"

I saw an instance of this on the first WebStorm start of the day. No closer to a full "Steps to Reproduce".

**Comment by timo-reymann** [comment]
You were a bit to fast (again), latest snapshot including the changes is [2021.08.06-369](https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot/131514) still pending approval :(

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.07-374

### About: "Editor tabs don't always get ..."

Identical results as version MJML Support 2021.08.06-367. (Baseline test as preferred. Second test: files return as preferred, but with the "Preview is not available" graphic for the one set for rendering.)

### About: "WebStorm restores with the same editor"

The loss-of-files condition happened on the first Webstorm start of the day again. The one file that opens is always the right-most of the files in each editor window.

I hibernate the operating system overnight each night. Maybe, there's a configuration file that isn't saved for hibernation? Seems like a "long-shot".

**Comment by timo-reymann** [comment]
What you can try for the restore of the order: Close all files, change the mode(s) to the desired and try again. I am not sure how the state is handled with plugin updates/hibernation.

**Comment by GarryFlemings** [comment]
About: "WebStorm restores with the same editor"

On a typical night, I fully shut down WebStorm before I hibernate Win10. Last night (Aug 9), I closed the project but did not dismiss the "Welcome to WebStorm" window (a dialog box listing all previously opened projects--or some of them--and giving me the option to open any). This morning (Aug 10), when I opened the project, all files opened. Useful?

Is this something MJML Support can affect? If not, perhaps it belongs with JetBrains.

**Comment by timo-reymann** [comment]
Nope, file opening behaviour etc. is outside the scope of this plugin. This might be sth for a bug report at JetBrains.

**Comment by timo-reymann** [comment]
For the "Preview not available"-problem the last commit adds a fix for this, its available with 2021.08.10-376

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.10-376

### About: "Editor tabs don't always get ..."
Identical results as version MJML Support 2021.08.06-367. (Baseline test as preferred. Second test: files return as preferred, but with the "Preview is not available" graphic for the one set for rendering.)

About: "WebStorm restores with the same editor"

Baseline test condition: Repeated. Same observations (as preferred).

Second test condition: Repeated.

Observed:

- Rendering is restored.
- All ten files reappear in the previous tabs and order. The MJML file previously in "Preview only" mode is in "Preview only" mode (as preferred).
- All other MJML files (previously in "Editor only" mode) are in "Editor only" mode (as preferred).

😀

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://no.where">2021.10.101</a>

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://no.where">2021.10.101</a>

**Comment by GarryFlemings** [comment]
Status: I worded this ticket implicitly including a bet the condition I reported as "Editor tabs don't always get ..." and the other condition "WebStorm restores with the same editor ..." would be the same. It was a bad bet. I consider "Editor tabs don't always get ..." closed. This entry is only about  "WebStorm restores with the same editor ..."

Per your suggestion, I opened https://youtrack.jetbrains.com/issue/IDEA-275900?clearDraft=true&description=%0A%0AWS-212.4746.80,%20JRE%2011.0.11%2B9-b1504.13x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%202400.0x1350.0,%201920.0x1080.0,%201920.0x1080.0

If JetBrains needs my permission for you to read that ticket, you have that permission. I'll tell them separately if preferred.

They asked, "Does the problem reproduce when the MJML Support plugin is disabled?" That led to this.

WebStorm status: Two editor windows, left and right. Between them, seven tabs. One window has three .mjml files and a .txt file. The other window has two .mjml files and a .html file.

I disabled MJML Support.

New WebStorm status: Only tabs for the non-.mjml files remain. Those are the .txt and .html files.

This might be the same condition described here as "WebStorm restores with the same editor ..."

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.09.02-408

### Wording repeated
I consider half of the original wording of this ticket is closed--the wording "Editor tabs don't always get ..." This information relates entirely to the remaining wording (repeated here from the start of this stream):

- WebStorm restores with the same editor windows (always left and right in my usage), but only one tab each, always different files and from the project, presumably each of them one of the files from the respective window.

### Related ticket

https://youtrack.jetbrains.com/issue/IDEA-275900?clearDraft=true&description=%0A%0AWS-212.4746.80,%20JRE%2011.0.11%2B9-b1504.13x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%202400.0x1350.0,%201920.0x1080.0,%201920.0x1080.0

### New information

Tonight, I saw MJML Support 2021.09.02-408 available for the first time. At the time I upgraded, I was probably using MJML Support 2021.08.05-361. Numerous files were open in tabs. I restarted WebStorm. Only three files--none of them MJML--returned when WebStorm returned. They were one each a .text, .html. and .toml file. Files in tabs not restored were all .mjml files. The files on disk were not affected; their tabs in the editor were lost.

Perhaps that behavior was attributable to -361. I tested -408 with only one instance of WebStorm running. WebStorm had two editor windows. In one window was a .txt, .html, and .mjml file; in the other window was a .toml, and two .mjml files.

Consistent with past testing, I closed WebStorm. In this case, I used File > Close Project, and then closed the "Welcome to WebStorm" dialog box.

I restarted Webstorm and opened the same project.

Editor tabs for all six files returned (as expected).

This ticket is already closed. The status is reasonable.

**Comment by GarryFlemings** [comment]
Let's reopen, please.

### Used versions
- Windows 10 Home 20H2 19042.1165
- WebStorm 2021.2 #WS-212.4746.80, built on July 23, 2021
- MJML Support 2021.09.08-416

### New information

Last night, I saw MJML Support 2021.09.08-416 available for the first time; I updated. I updated from MJML Support 2021.09.02-408. Three files were open in editor tabs--one each .txt, .html, and .mjml. I restarted WebStorm. Only two file tabs--the .txt and .html--returned when WebStorm returned (not expected).

I added the .mjml file to the editor. I restarted WebStorm via

- WebStorm File > Close project
- Close the "Welcome to WebStorm" dialog box.
- Start WebStorm.

All three file tabs returned (as expected).

### Speculation

When MJML Support can run its "close" routine, .mjml files get proper handling. Maybe WebStorm doesn't signal the plugin to run its "close" process when I click "Restart IDE" (or similar wording) in the WebStorm Settings > Plugins dialog box after updating a plugin.

**Comment by timo-reymann** [comment]
It might take some time till i will take a look at this ticket.
This is rather low priority now and hard to figure out (and new features have prio over this) :)

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.09.11-422

### New information

While I understand both the low priority for this ticket and the difficulty in pinning down the code to change, if I document everything I know or experience, the task might get easier. Eventually. I'm in no rush.

Tonight, I saw MJML Support 2021.09.11-422 became available for the first time; I updated. I observed something new.

The process, once the WebStorm > File > Settings (dialog box) > Plugins (tab) showed me an MJML Support update was available.

- I clicked "update" for MJML Support. I saw a progress bar during some activity. When that completed ...
- I clicked the "Restart IDE" button. "Behind" the above dialog box, my editor windows and all my file tabs changed. During this time, all my MJML file tabs disappeared in the editor panes. Then, the above dialog box disappeared and this one showed:
![image](https://user-images.githubusercontent.com/14095071/133173486-5cb1e1cb-f618-4abd-8bf6-5d2cf82593c6.png)
- I clicked the depicted Restart button. Shortly, WebStorm was back on the screen with the same editor panes and file tabs as before I clicked the above Restart button.

The new part: The tabs disappear during the transition from one version of MJML Support to the next and before the WebStorm restart process starts.

Uncertainty: Now that I read the above again, I consider it possible the editor panes and file tabs changed behind the dialog box during the progress bar and before I clicked the "Restart IDE" button. I consider that important. I don't know how to go back. I'll watch on the next update and report then.

I hope this and other information eventually helps you find the code to tweak!

**Comment by timo-reymann** [comment]
When you do a plugin update what intellij does:

1. unloading the old version
2. loading the new version
3. restart

the problem is the time between unloading and loading there is no control for the plugin how things are handled, so the "custom editor tabs" are simply thrown away. While this is not a good thing, there is no way around it unfortunately.

**Comment by timo-reymann** [comment]
@GarryFlemings Any updates on this?

**Comment by GarryFlemings** [comment]
Good question.

## Current status

Windows 10 Home 21H1 19043.1415
WebStorm 2021.2 #WS-212.4746.80 built on July 23, 2021
MJML Support 2021.11.15-531

Related ticket https://youtrack.jetbrains.com/issue/IDEA-275900?clearDraft=true&description=%0A%0AWS-212.4746.80,%20JRE%2011.0.11%2B9-b1504.13x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%202400.0x1350.0,%201920.0x1080.0,%201920.0x1080.0: The most recent update was mine, dated Sep 14, 2021. No JetBrains response.

In the above discussion on Sep 3, I indicted I considered it reasonable to close this ticket because all behavior I originally cited was behaving as expected.

Current behavior: I repeated all tests described to this point. All results were as preferred. I continue to support the Sep 3 assessment.

On Sep 9 I additionally cited behavior associated with updating MJML Support. I needed to upgrade today and did. All behavior was as expected.

Let's close this ticket again. I'll close the JetBrains ticket, too. Thanks!
