### ISSUE TITLE
inconsistent file opening

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#54]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

- Windows 10 Home 20H2 19042.1151
- WebStorm 2021.1.3 #WS-212.4746.80 built on July 23, 2021
- MJML Support 2021.08.05-361

### Test condition

The task is to use one way of opening an existing MJML file in an existing editor window and a new editor tab.

Terms

- _Project view:_ Among WebStorm views, the list of folders and files in the project folder. On my screen and in many WebStorm depictions of typical screens, it is on the left edge of the screen.
- _Dropped file:_ Among filenames in the _project view_, a filename for an existing plain-MJML file. I used the same file for all testing described here; this file is not a CSS file and has no `<mjml><mj-body></mj-body></mjml>` tags. So named because I'll "drag-and-drop" the filename.
- MJML Support "Editor/Preview/Both" mode: In MJML Support, the mode of support corresponding to icons with Intellisense labels "Editor only", "Editor and Preview", and "Preview only".
- _Text portion of an editor tab:_ Among parts of a WebStorm editor window (e.g., a depiction of tabs with filenames available for editing, MJML Support icons (for some tabs), a series of line numbers for code lines, etc.), the part of the tab (and window) displaying the file's code and supporting editing.

## Expected Behavior

When I put a _dropped file_ in the _text portion of an editor tab_, the _dropped file_ opens in the same editor window, in a new editor tab, and in MJML Support "Editor only" mode. The _MJML Support "Editor/Preview/Both" mode_ of the existing file in the editor tab has no effect on this process.

#### First baseline test condition, _dropped file_ put in the _text portion of an editor tab_ showing an MJML file in "Editor only" mode

Observed: The _dropped file_ opens in the same editor window, a new editor tab, and in MJML Support "Editor only" mode (as preferred).

#### Second baseline test condition, _dropped file_ put in the _text portion of an editor tab_ showing an HTML file

EDIT:
~~Observed: Same as baseline test condition #1 (as preferred).~~
Observed: Same as "First baseline test condition" (as preferred).

#### Test condition, _dropped file_ put in the _text portion of an editor tab_ showing an MJML file in MJML Support "Preview only" mode

Observed: Either of

- A blank screen (non-preferred)
- An uneditable presentation of the _dropped file_ in a different font (non-preferred)

In both cases, the MJML Support icons indicate "Preview only" mode.

In both cases, clicking the "Editor only" icon puts the tab in "Editor only" mode showing the _original_ file (not the _dropped file_). This is (non-preferred) different from the prior tab status: original file in "Preview only" mode.

Potential for further testing: I have not tested for loss of unsaved data in the original file through this process.

More about the blank screen:

- In all cases that I remember a blank screen and I clicked the "Editor only" icon, I got (at least almost) the same result described above for clicking that icon. The file whose code came on-screen never had `<mjml><mj-body></mj-body></mjml>` tags (consistent with an include file; I always dropped include files). Rendering such a file creates a blank screen. Maybe in those cases, the _dropped file_ showed. That's distinct from the above cases, in which the tab's _original_ file always appeared in the editor tab.
- As I write, I have not found the "Steps to Reproduce" for the blank screen. When I put _dropped file_ on a file in "Editor only" mode (either the root file or an include file), I saw the _dropped file_ in "Editor only" mode. When I dropped on an MJML file on a file in "Preview only" mode (root file or an include file), I saw the _dropped file_, uneditable and in a different font.

### Important Factoids

This may be related to #53 "Webstorm inconsistent in setting ..."

**Comment by timo-reymann** [comment]
For the blank screen first: This should display something like this in the newest snapshot (once approved by JetBrains):
![image](https://user-images.githubusercontent.com/21024948/128591682-520bda66-f94a-4852-bde3-86bc4d099475.png)

When you reopen a mjml file it uses the previous editor state for that run, if you haven't opened it yet it will default to "editor only". This might be something to combine with (#53) setting how this should be handled

The "drag and drop logic for editors" is outside the scope of this plugin and can not be affected with the current solution.

> I saw the dropped file, uneditable and in a different font.
Can you please provide a screenshot for this? I can't figure out what is going wrong here

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.17-403

**First baseline test condition, dropped file put in the text portion of an editor tab showing an MJML file in "Editor only" mode**

Repeated. Results as above. As preferred.

**Test condition, dropped file put in the text portion of an editor tab showing an MJML file in MJML Support "Preview only" mode**

Repeated.

Distinct from the past: Clicking the "Editor only" icon for the _dropped file_ tab puts the tab in "Editor only" mode showing the _dropped_ file (previously the _original_ file). As preferred.

New issue: The _dropped file_ tab is inconsistent about the MJML Support "Editor/Preview/Both" mode it uses.

Sequence of three: Each time, I dropped an icon for an MJML file capable of displaying a preview (not a CSS file) and already with a tab in the left editor; there's variation in this sequence as to the mode of the display in the left editor. Each time, I dropped on an HTML file in the right editor.

(Apologies to Markdown table notation, which didn't work for me here.)
.......................... | With the left editor tab in _this_ mode, | the right editor opened in _this_ mode.
.......................... | .......................................................................... | ............................................................................
first drop....... | ........................"Editor only"......................... | ........................"Editor only"......................... 
second drop | ......................"Preview only"........................ | ......................"Preview only"........................ 
third drop..... | ........................"Editor only"......................... | ......................"Preview only"........................ 

First drop: Probably preferred; your call.
Second drop: Might be okay; your call.
Third drop, same condition as the first: Result inconsistent with the first drop under the same condition; consistent with the second drop under a different condition. Might be okay; your call.

**Comment by timo-reymann** [comment]
Alright so right now, the behaviour is the following:

The state of an file is persisted across file opens and restarts with the same idea (e. g. when using IntelliJ IDEA and WebStorm they both have a different state for the same project).
If there is no state (older version of the IDE or the file hasn't been opened yet) the default "Both mode" with the Editor and Preview is shown.

This is intended and currently the "desired behaviour".
