### ISSUE TITLE
mobile preview and desktop preview are too similar

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#55]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

- Windows 10 Home 20H2 19042.1151
- WebStorm 2021.1.3 #WS-212.4746.80 built on July 23, 2021
- MJML Support 2021.08.05-361

## Test condition

Load this file into WebStorm.

[size.txt](https://github.com/timo-reymann/intellij-mjml-support/files/6948602/size.txt)

Same text in https://mjml.io/try-it-live/Wupoth9GGfk

Same text also below.

```
<mjml>
  <mj-head>
    <mj-breakpoint width="450px" />
  </mj-head>
  <mj-body width="900px" >
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Note that the body width should be 900px and the email should always go to mobile mode at 450px wide.

## Expected behavior

Try-it-Live and MJML Support preview the same code the same. (Realistically: "close" to the same!) This applies in both desktop and mobile modes.

## Try-it-Live behavior

Desktop

![image](https://user-images.githubusercontent.com/14095071/128588641-874cf593-fdfa-48a9-873d-1528d0f00aaa.png)

Mobile

![image](https://user-images.githubusercontent.com/14095071/128588659-726b3aec-7b6a-4223-a1d3-fdc816664167.png)

### WebStorm and MJML Support behavior

Desktop

![image](https://user-images.githubusercontent.com/14095071/128588695-fa2f465e-d962-4799-90e6-39ab0140fd72.png)

Mobile

![image](https://user-images.githubusercontent.com/14095071/128588706-b62df6a9-14db-4f5d-a171-5c5c1c48d832.png)

### Interpretation

- The two desktop previews are the same (or close, as desired).
- The amount of difference between the two Try-it-Live images looks reasonable (absent any detailed measuring, as desired).
- The amount of difference between the MJML Support previews looks understated (non-desired).
- The two mobile previews are neither the same nor close to the same (non-desired).
- This condition affects all the MJML templates I've checked.

**Comment by timo-reymann** [comment]
Maybe try-it-live depends heavily on the screen size?

I tried it with fullscreen and get the following result:
![Peek 2021-08-07 10-00](https://user-images.githubusercontent.com/21024948/128593315-56310d85-04d8-440a-8c0b-ffa3b6d404e3.gif)

**Comment by GarryFlemings** [comment]
### Used versions
- MJML Support 2021.08.17-403

Given what you see, it's right to close this.

I rechecked in split-screen, with this file in the right editor window, and with WebStorm occupying the full screen except approximately 15mm all around. My display is native to and using 1920x1600 resolution. Distinct from the above, I get the same preview in both laptop and desktop modes. The first line of that display ends with "tempor", matching the first of the screen clips included above.

I didn't notice it before, but the preview window is perhaps 1 cm wider in desktop mode, but not enough for the first word of the second line to flow to the first line. The WebStorm window and the pane with the list of files (far left) both stay the same width either way; the left editor expands or contracts accordingly.

In full-screen, the preview window is the same size in either desktop or mobile mode, with the same display.

Your call. If your can't see it, it's hard to fix!

**Comment by GarryFlemings** [comment]
More info.

In all cases: I have a preview-able MJML file open in the left WebStorm editor window (not an include file)

1: Clicking the "Editor only" icon, I see the code of the email.

2: Clicking the "Desktop Preview" icon, I see

**Comment by timo-reymann** [comment]
For the fullscreen is intended to be not desktop or mobile optimized. It simply uses all the screen space it can get.

For the mobile/desktop the widt is currently 400/800px as long there is enough screen space, under some resolution the size is ignored by the IDE (Java Swing).

![image](https://user-images.githubusercontent.com/21024948/132484953-f90912fd-5c3a-44cc-a0bf-eeb5e90e3c30.png)
![image](https://user-images.githubusercontent.com/21024948/132484981-a4dd2668-2865-4979-a48e-533219c703e7.png)

**Comment by timo-reymann** [comment]
So i don't see anything i could do here 😅

**Comment by GarryFlemings** [comment]
Background: This issue correctly reports that the mobile preview looks the same as the desktop preview (or "too close") in "Preview Only" mode in a wide editor pane. With MJML Support version 2020-09-11.422 (presumably soon to be reflected in a stable release), this remains true. This isn't a bad thing.

With MJML Support in "Editor and Preview" mode, the mobile and desktop previews are appropriately different. And valuable.
