### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#58]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

Used versions
Windows 10 Home 20H2 19042.1165
WebStorm 2021.2 #WS-212.4746.80 built on July 23, 2021
MJML Support 2021.08.17-403 (-405 still pending)

## Problem description

IDE Fatal Error, stacktrace.txt:

[e.txt](https://github.com/timo-reymann/intellij-mjml-support/files/7050066/e.txt)

### Steps to Reproduce

~~Sorry; no idea. When I noticed it, it was 14 minutes later. Good luck!~~

With a preview-able MJML file in the left editor window of Webstorm:

1. Clicking "Editor only" icon, I see the source code of the email. (as desired)

2. Clicking "Desktop Preview" icon, I see the following IDE Fatal Error attributed to 2021.08.17-403. A copy of "stacktrace.txt":

[e1.txt](https://github.com/timo-reymann/intellij-mjml-support/files/7050289/e1.txt)

(This is a separate cut-and-paste, though skimming, it looks very close--identical?--to the above.)

On-screen, I continue to see the source code for the email.

3. Close and restart WebStorm; it opens to the same file. The "Editor only" icon has the grey background. Clicking the "Desktop Preview", "Mobile Preview", or "Show HTML" icons have no effect. In all cases, I continue to see the email source code on the screen. There is no indication of either an "IDE Fatal Error" or a "Problem" (the list of MJML errors your code creates).

4. Why do I include this with this ticket? Before I could rigorously record all the keystrokes,

  - Clicking the "Desktop Preview" icon presented an expectable rendering. (as expected)
  - Clicking the "Mobile Preview" icon presented the same rendering. (not expected; consistent with the above)
  - Clicking the "Show HTML" icon presented a blank screen. (not expected) In this status, both the "Desktop Preview" and "Mobile Preview" icons had no effect. (not expected)
  - Clicking the "Editor only" icon restored the email source code. (as expected)

In each of the above cases when the email source code was on the screen, the normal editing function was also available.

I saw the above behavior twice before deciding to report it.

**Comment by timo-reymann** [comment]
Could you please provide a sample mjml file for this error?
From the stack trace it says sth like "Wrong line separators", while creating the html preview, that depends on the generated mjml for the current document.

**Comment by GarryFlemings** [comment]
Sorry. I don't have a copy. Let's reopen if it happens again.
