### ISSUE TITLE
Problem with umlauts

### ISSUE THREAD

**Issue by timo-reymann** [timo-reymann/intellij-mjml-support#59]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Used versions

* MJML: 1.17.0
* IDE: PhpStorm 2021.2 #PS-212.4746.100, built on July 28, 2021)
* Host OS: Windows

## Problem description
Umlauts doesnt work in UTF8 file

## Expected Behavior

Result should be rendered correctly

### Actual Behavior

![image](https://user-images.githubusercontent.com/21024948/130944887-0320b856-bd0d-4fbf-a6b7-cfe1ceeb7cfa.png)
![image](https://user-images.githubusercontent.com/21024948/130944901-c9a5ff1a-03da-4214-bab3-b2aa31b54fab.png)

### Steps to Reproduce

Create UTF8-file for mail and add umlauts.

*Reported by Stefan Kilp by mail*

**Comment by capetrel** [comment]
Hi,
I have the same probleme but with all accented caracters (i'm french), but if i use the html entities, the preveiw display the good char (see screenshot below).
![capture-mjml-bug](https://user-images.githubusercontent.com/18441194/132831674-0f7eb277-5849-414c-ab63-0049c8c1dc73.PNG)
![capture-mjml-bug-html-entities](https://user-images.githubusercontent.com/18441194/132831677-d7d43dda-ceab-4bef-9a5e-e80b4a5029fe.PNG)

**Comment by timo-reymann** [comment]
@capetrel Could you provide more information about your environment?

Especially what version of the plugin are you using?
Which OS?

What would help really much would be a sample file to reproduce this, because i can't really reproduce this. Best thing would be a git repository with the file in it for testing.

**Comment by capetrel** [comment]
Hi, thanks for response.
Sorry i forgot to give my environment:
OS : windows 10 21H1, build 19043.1165
IDE : IntelliJ IDEA 2021.2 build #IU-212.4746.92
plugin version : 1.17.0

Here is a [link to a repo with the file to test](https://github.com/capetrel/mjml-test).

**Comment by timo-reymann** [comment]
Hi capetrol,

thank you for the details and the repo. As far as i see there  are no more 'special chars' can you please add some?

Of course i could decode the HTML entities but that might influence the result.

**Comment by capetrel** [comment]
Sorry, for this late answer, i was busy with my work. i have replace the HTML code by the 'special char' in the repo.

**Comment by timo-reymann** [comment]
Ok so first analysis:
- does not happen on MacOS
- does not happen on Linux

It seems to be a "windows exclusive problem", i will evaluate that.

**Comment by timo-reymann** [comment]
As i can't reproduce it and there is a workaround (and maybe even better version to use html entities instead for older mail clients etc.) i will close this for now.
