### ISSUE TITLE
support dynamic adjustment of preview window size

### ISSUE THREAD

**Issue by GarryFlemings** [timo-reymann/intellij-mjml-support#63]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Desired use case

An MJML author does not allocate their full screen width WebStorm. They open WebStorm with a single editor window, open an MJML file there, and put the window in MJML Support "Editor and Preview" mode. MJML Support should make editing as convenient as possible for this author.

#### Existing behavior

On my computer, it seems the mobile width is always the same, close to 390px. When the WebStorm window has around 860px and reserves 200px for the Project pane, the Editor pane becomes a comically small 240px. With one of my files, the line numbers were around 65px of that! 😉

Perhaps it's a reasonable use case that the author would want to optimize other mobile widths.

In my case, I tried moving my cursor over the boundary between the editor pane and the preview pane. I did not see indication I could change the pane sizes by moving the boundary. It was a natural attempt to make; WebStorm supports that editing motion between two vertical editor windows.

#### Potential new features for "Editor and Preview" mode

1. Support the author moving the boundary between the editor pane and the preview pane to see other mobile sizes (matching WebStorm between vertical editor panes).
2. As an author reduces the size of WebStorm window and starting when the size of the editor pane matches the size of the preview pane, size width of the editor pane and preview pane equally.

**Comment by timo-reymann** [comment]
Thats indeed a good idea!

Option 2 seems to be out of scope for me (thats handled outside of the plugins control).

Adding a third option to allow flexible resizing would be the easiest and most effective I guess. Best with automatically switching when a resize occures.

I will take a look, i think it should be relatively simple to implement.

**Comment by timo-reymann** [comment]
Sneak preview:
![Peek 2021-09-11 16-17](https://user-images.githubusercontent.com/21024948/132950979-898bb6b7-1d1d-4af4-ab9e-048289e70c02.gif)

The little stuttering (black screen parts) are from Swing - moving complex content is not realtime. Thats a known thing (and there is no real solution as far as i know)
Workaround would be to simply hide the preview while resizing, but that might kill the feature for many devs who want to see when their mails break.

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2021.09.11-422</a>

**Comment by GarryFlemings** [comment]
This is a very nice improvement in 2021.09.11-422! Great!
