### ISSUE TITLE
How can i open local images with relative path on preview?

### ISSUE THREAD

**Issue by luispaulotoniettefranca** [timo-reymann/intellij-mjml-support#86]
When using relative path's to images, can't preview them.

![image](https://user-images.githubusercontent.com/12602917/139458373-c3f08df8-95c5-4a4b-b013-895015b3eb64.png)

`<mj-image width="163px" src="images/FIA0106_363_PUL-02.png"></mj-image>`

![image](https://user-images.githubusercontent.com/12602917/139458480-3d10acd8-fa08-4b13-8ef5-0b0251c99e53.png)

**Comment by timo-reymann** [comment]
Hi, this is currently not supported.

**Comment by timo-reymann** [comment]
Whats the usecase behind this? As mjml does not support local images (because of restrictions in HTML mailing)?

**Comment by tjunnone** [comment]
During development, it's convenient to be able to preview with local images before uploading the final versions to a CDN or server.

**Comment by timo-reymann** [comment]
Fair point, so in your case you would have a e. g. external build tool? That seems like a valid use case, i will take a look how to implement this.

**Comment by timo-reymann** [comment]
Current situation/Analysis:
- Plugin is using the [JCEF Framework](https://plugins.jetbrains.com/docs/intellij/jcef.html)
- For loading html the IDE creates a file url with know content that gets loaded on request


Possible solutions:
- Inline images as base64 before creating mjml
- Replace all images to base64 in the html to render
- Write custom handler on JCEF side to fake the image loading

**Comment by timo-reymann** [comment]
New setting:
![image](https://user-images.githubusercontent.com/21024948/139660637-063bf8b6-f5f4-4cb5-994e-17303ac3c4d7.png)

It will be **disabled by default** to prevent assumptions from unexperienced mjml users that local images might work on a magic way (by inlining etc).

The plugin configuration for the project is stored as an xml file under _.idea/mjmlSettings.xml_. So it is possible to check it into version control allowing the entire team to share the setting or synchronize it across multiple machines.

**Comment by timo-reymann** [comment]
Will be available with [1.20.0](https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/stable/143970) after JetBrains approval.

**Comment by luispaulotoniettefranca** [comment]
Thanks, but i can't download or install the 1.20.0 version on PHPStorm. Only 1.17.0 is available.

**Comment by luispaulotoniettefranca** [comment]
Sorry. But using relative paths i can't get the image preview.

![image](https://user-images.githubusercontent.com/12602917/141602474-93a93be0-d5c5-49b2-bf8d-2d14a21b3910.png)
![image](https://user-images.githubusercontent.com/12602917/141602482-c7e6ee96-5e93-4548-80d2-de18e0d820da.png)
![image](https://user-images.githubusercontent.com/12602917/141602486-c2aa7863-282e-4ba5-a0ec-ee21550267ee.png)

**Comment by timo-reymann** [comment]
@luispaulotoniettefranca have you also enabled it in the settings?

**Comment by luispaulotoniettefranca** [comment]
Yes. I did.

**Comment by timo-reymann** [comment]
Can you provide a more insights about the entire project structure etc?

**Comment by luispaulotoniettefranca** [comment]
I'm sending my project to your email, ok?

**Comment by timo-reymann** [comment]
Got it, i will take a look and come back at you

**Comment by timo-reymann** [comment]
HI @luispaulotoniettefranca,

with the zip file unpacked you sent me, it works:
![image](https://user-images.githubusercontent.com/21024948/142063508-ca82a551-ae74-4399-8b8b-b6fa56d832be.png)

Is this the complete structure you use in IntelliJ? If so i can't find sth that should not be working ...

**Comment by timo-reymann** [comment]
As i gotten no feedback for 2 weeks i assume this is now fixed.
